"""Added messages models

Revision ID: 1c89c1398388
Revises: 7a775e705e58
Create Date: 2024-03-29 13:52:06.267525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c89c1398388'
down_revision: Union[str, None] = '7a775e705e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('role', sa.Column('permissions', sa.JSON(), nullable=True))
    op.drop_column('role', 'permissons')
    op.add_column('user', sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'registerd_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registerd_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'registered_at')
    op.add_column('role', sa.Column('permissons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('role', 'permissions')
    op.drop_table('messages')
    # ### end Alembic commands ###
